### ISSUE TITLE
Support okhttp3.Response return type

### ISSUE THREAD

**Issue by shaburov** [touchbit/retrofit-veslo#6]
During testing, calls are made to live/ready probes to obtain information about the state of the service under test. Different data (body/headers) are returned in different service states and it would be convenient to use raw `okhttp3.Response` instead of `DualResponse <RawBody, RawBody>`.

```java
public interface ApiCli {

    @GET("/v2/example")
    @Headers({"Content-Type: application/json"})
    okhttp3.Response get();

}
```

**Comment by shaburov** [comment]
Retrofit implementation restriction. See [issue](https://github.com/square/retrofit/issues/3698).
```
java.lang.IllegalArgumentException: 'okhttp3.Response' is not a valid response body type. Did you mean ResponseBody?
    for method JavaTypeAdapterFactoryClient.returnRawResponseType

	at retrofit2.Utils.methodError(Utils.java:54)
	at retrofit2.Utils.methodError(Utils.java:43)
	at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:70)
	at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
	at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
	at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
	at com.sun.proxy.$Proxy28.returnRawResponseType(Unknown Source)
```
